api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'ideas', views.IdeaViewSet)

app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

cloudsaver/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from ideas import views
from django.contrib.auth.models import User
from rest_framework import serializers, viewsets, routers

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('ideas/', include('ideas.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    #path('logout/', views.logout, name='logout'),
    path('', include('social_django.urls', namespace='social')),
    #path('tinymce/', include('tinymce.urls')),
    path('api', include('api.urls'), name='api'),
]

ideas/urls.py
from django.urls import path, include, re_path
from django.urls import reverse
from . import views
from .models import Idea
from rest_framework import routers


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'api', views.IdeaViewSet)

app_name = 'ideas'

urlpatterns = [
    #path('api', include(router.urls)),
    #path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('details/<int:pk>/', views.DetailMiniView.as_view(), name='detailmini'),
    path('<int:pk>/edit/', views.EditView.as_view(), name='edit'),
    # path('<int:id>/proposal/', include('tinymce.urls'), name='editor'),
    path('tinymce/', include('tinymce.urls')),
    path('add/', views.addView, name='add'),
    path('addgroup', views.AddGroup.as_view(success_url='/ideas/'),
         name='addgroup'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('results/', views.SearchResultsView.as_view(), name='search_results'),
    path('<str:slug>/', views.GroupView.as_view(), name='groupview'),
    
    path('contact', views.ContactView.as_view(), name='contact'),
    path('', include('social_django.urls', namespace='social')),
    
]

SOCIAL_AUTH_URL_NAMESPACE = 'social'

ideas/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
import datetime

# Create your models here.

class Ideas_Group(models.Model):
    category_text = models.CharField(max_length=30, unique=True)
    # votes = models.IntegerField(default=0)

    def __str__(self):
        return self.category_text

class Idea(models.Model):
    idea_title = models.CharField(max_length=30)
    idea_text = models.CharField(max_length=200)
    idea_repo = models.URLField(max_length=80, blank=True, null=True)
    idea_owner = models.CharField(max_length=30, blank=True, null=True)
    idea_status = models.CharField(max_length=30, blank=True, null=True)
    content = HTMLField('content')
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    group = models.ForeignKey(Ideas_Group, on_delete=models.CASCADE)
    
    def __str__(self):
        return "%s by %s => %s" % (self.idea_title, self.idea_owner, self.idea_text)

    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)
    

ideas/forms.py
from django import forms
from ideas.models import Idea, Ideas_Group
from django.forms.models import inlineformset_factory

class IdeasForm(forms.ModelForm):
    idea_title = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':"do you have a name for your idea",
        'aria-describedby':"basic-addon1",}))

    idea_text = forms.CharField(widget=forms.Textarea(attrs={
                                    'class':'form-control',
                                    'placeholder':"what s the idea man",
                                    'aria-describedby':"basic-addon1",
                                    'rows':"2"}),
                                max_length=200,)

    group = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':"Category",
        'aria-describedby':"basic-addon1",}))

    idea_repo = forms.URLField(widget=forms.URLInput(attrs={
        'class':'form-control',
        'placeholder':"repo",
        'aria-describedby':"basic-addon1",}),
                               required=False)

    class Meta:
        model = Idea
        fields = ('idea_title',
                  'idea_text',
                  'group',
                  'idea_repo',)

    def clean(self):
        group, created = Ideas_Group.objects.get_or_create(
                    category_text=self.cleaned_data.get('group'))
        self.cleaned_data['group'] = group
        return super(IdeasForm, self).clean()

    def save(self, commit=True):
        group, created = Ideas_Group.objects.get_or_create(
                    category_text=self.cleaned_data.get('group'))
        print(11111)
        self.cleaned_data['group'] = group
        #self.group = group_new.id
        print(222222)
        return super(IdeasForm, self).save(commit)

class EditIdeasForm(forms.ModelForm):
    idea_title = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':"do you have a name for your idea",
        'aria-describedby':"basic-addon1",}))

    idea_text = forms.CharField(widget=forms.Textarea(attrs={
                                    'class':'form-control',
                                    'placeholder':"what s the idea man",
                                    'aria-describedby':"basic-addon1",
                                    'rows':"10" }),
                                max_length=200,)

    idea_repo = forms.URLField(widget=forms.URLInput(attrs={
        'class':'form-control',
        'placeholder':"repo",
        'aria-describedby':"basic-addon1",}),
                               required=False)

    #idea_repo.widget.attrs.update(
    class Meta:
        model = Idea
        fields = ('idea_title',
                  'idea_text',
                  'idea_repo',
                  'idea_owner',
                  'idea_status',
                  'group')


    #def save(self, commit=True):


     #   if commit:

class AddGroupForm(forms.ModelForm):
    category_text = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':"New Group",
        'aria-describedby':"basic-addon1",}))

    class Meta:
        model = Ideas_Group
        fields = ('category_text',)

ideas/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from rest_framework import viewsets
from rest_framework.views import APIView
from .serializers import IdeaSerializer
from django.urls import reverse
from django.utils import timezone
import datetime

from .models import Idea, Ideas_Group
from .forms import IdeasForm, EditIdeasForm, AddGroupForm

class IdeaViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows ideas to be viewed or edited.
    """
    queryset = Idea.objects.all().order_by('-pub_date')
    serializer_class = IdeaSerializer

class IdeaApiView(APIView):

    def get(self, request, pk=None):
        res = get_object_or_404(Idea, pk=pk)
        
        return Response ({"msg": res, status:status.HTTP_200_OK})
 
# Create your views here.
class IndexView(generic.ListView):
    # model = Idea
    template_name = 'ideas/index.html'
    context_object_name = 'latest_ideas_list, ideas_list'
    
    #latest_ideas_list = Idea.objects.order_by('-pub_date')
    #paginator = Paginator(latest_ideas_list, 10)
    #latest_ideas_pages = paginator.page(1)
    def get(self, request):
        
        form = IdeasForm()
        latest_ideas_list = Idea.objects.order_by('-pub_date')
        paginator = Paginator(latest_ideas_list, 10)
        latest_ideas_pages = paginator.page(1)
        # ideas_list = Idea.objects.order_by('-pub_date')
        context = {
            'latest_ideas_list': latest_ideas_list[:6],
            'ideas_list': latest_ideas_pages,
            'form': form
        }
        return render(request,
                      self.template_name,
                      context)
    
    def post(self, request):
        if request.method == 'POST':
            # create a form instance and populate it with data from the request:
            print(request.POST)
            form = IdeasForm(request.POST)
            print(form.is_valid())    
            # check whether it's valid:
            if form.is_valid():
                ideapost = form.save(commit=False)
                #ideapost.pub_date=timezone.now()
                print(form.cleaned_data['group'])
                ideapost.save()

        latest_ideas_list = Idea.objects.order_by('-pub_date')[:6]
        paginator = Paginator(latest_ideas_list, 10)
        latest_ideas_pages = paginator.page(1)
        context = {
            'latest_ideas_list': latest_ideas_list,
            'ideas_list': latest_ideas_pages,
            'form': IdeasForm(),
        }
        return render(request,
                      self.template_name,
                      context)
            # if a GET (or any other method) we'll create a blank form
        #else:
        #   form = IdeasForm() 

        
class DetailView(generic.DetailView):
    model = Idea
    template_name = 'ideas/details.html'

    
class DetailMiniView(generic.DetailView):
    model = Idea
    template_name = 'ideas/details_miniview.html'

    
class EditView(generic.UpdateView):
    model=Idea
    template_name = 'ideas/idea_update_form.html'
    form_class = EditIdeasForm
    template_name_suffix = '_update_form'
    #redirect_url="ideas/details.html"
    def get_success_url(self):
        return reverse('ideas:index')

# def deleteView(request, id):
#     idea = Idea.objects.get(pk=id)
#     template_name = 'ideas/index.html'
#     idea.delete()
#     render(request, template_name)

# TODO: delete idea from the update view
class DeleteIdea(generic.DeleteView):
    model=Idea
    template_name = 'ideas/idea_update_form.html'
    template_name_suffix = '_update_form'
    #success_url='/'
    def get_success_url(self):
        return reverse('ideas:index')
    
def addView(request):
    #model = Idea
    template_name = 'ideas/add.html'
    return HttpResponse("Hey your ideas are awesome.")


class GroupView(generic.ListView):
    model = Idea
    template_name = 'ideas_group_list.html'
    paginate_by = 10
    
    context_object_name = 'group_list'
    
    def get_queryset(self):
      category_slug = get_object_or_404(Ideas_Group,
                                        category_text=self.kwargs['slug'])
      return Idea.objects.filter(group=category_slug)    
    
    
class AddGroup(generic.CreateView):
    model = Ideas_Group
    form = AddGroupForm()
    fields = ['category_text']

    
class AboutView(generic.TemplateView):
    template_name = 'ideas/about.html'

    
class ContactView(generic.TemplateView):
    template_name = 'ideas/contact.html'

    
class LoginView(generic.TemplateView):
    template_name = 'ideas/login.html'

    
def login(request):
    return render(request, 'login.html')


def logout(request):
    logout(request)
    return render(request, 'logout.html')


class SearchResultsView(generic.ListView):
    model = Idea
    template_name = 'ideas/search_results.html'
    context_object_name = 'results_list'

    def get_queryset(self):
        query = self.request.GET.get('q')
        results_list = Idea.objects.filter(Q(idea_title__icontains=query) |
                                   Q(idea_text__icontains=query))
        return results_list

ideas/templates/ideas/.#add.html
iob@localhost.chaos.1513256:1579332314

ideas/templates/ideas/about.html
{% extends "common/base.html" %}


{% block container %}
<div class="container">
  
  <div class="row row-offcanvas row-offcanvas-right">
    
    <div class="col-xs-12 col-sm-9">
      <p class="pull-right visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
      </p>
      <div class="jumbotron">
        <h1>About</h1>
      </div>
      <div class="row">
        <p>Ideas and dreams. Comes out to you from nowhere. And sometimes they flow away with
            the same way. Keep your ideas save fly with them and find collaborators.</p>
      </div><!--/row-->
      
    </div><!--/.col-xs-12.col-sm-9-->
    
    {% block sidebar %}
    {% include "common/sidebar.html" %}{% endblock %}
  </div><!--/row-->
  <hr>
  
</div><!--/.container-->
{% endblock %}

ideas/templates/ideas/add.html
<h1>Have a new idea?</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'ideas:add' %}" method="post">
{% csrf_token %}

<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />

<input type="submit" value="Vote" />
</form>

ideas/templates/ideas/addgroup_form.html
{% extends "common/base.html" %}


{% block container %}
    <div class="container">
 
      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Add a new group of ideas</h1>
            {{ form.non_field_errors }}
            <form action="" method="post">
              {% csrf_token %}
              <div class="input-group" id="{{ form.category_text.id_for_label }}">
                <span class="input-group-addon" id="basic-addon1">Title</span>
                {{ form.category_text }}
              </div>
              
              </br>
              <button type="submit" class="btn btn-primary" name="save">Save</button>
            </form>
            
            <!--p>Ideas and dreams. Comes out to you from nowhere. And sometimes they flow away with
            the same way. Keep your ideas save fly with them and find collaborators.</p-->
          </div>
        </div><!--/.col-xs-12.col-sm-9-->
      </div><!--/row-->
      <hr>
    </div><!--/.container-->
{% endblock %}

ideas/templates/ideas/contact.html
{% extends "common/base.html" %}


{% block container %}
<div class="container">
  
  <div class="row row-offcanvas row-offcanvas-right">
    
    <div class="col-xs-12 col-sm-9">
      <p class="pull-right visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
      </p>
      <div class="jumbotron">
        <h1>Contact</h1>
      </div>
      <div class="row">
        <p>TODO</p>
      </div><!--/row-->
      
    </div><!--/.col-xs-12.col-sm-9-->
   
  </div><!--/row-->
  <hr>
  
</div><!--/.container-->
{% endblock %}

ideas/templates/ideas/details.html
{% extends "common/base.html" %}


{% block container %}
<div class="container">
  
  <div class="row row-offcanvas row-offcanvas-right">
    
    <div class="col-xs-12 col-sm-9">
      <p class="pull-right visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
      </p>
      <div class="jumbotron">
        <h1>{{ idea.idea_title }}</h1>
      </div>
      <div class="row">
        <ul>
          <li>{{ idea.idea_text }}</li>
        </ul>
        <ul>
          <li>{{ idea.group.category_text }}</li>
        </ul>
        <p><a class="btn btn-default" href="{% url 'ideas:edit' idea.id %}" role="button">Edit details »</a></p>
      </div><!--/row-->
      
    </div><!--/.col-xs-12.col-sm-9-->
    
    {% block sidebar %}
    {% include "common/sidebar.html" %}{% endblock %}
  </div><!--/row-->
  <hr>
  
</div><!--/.container-->
{% endblock %}

ideas/templates/ideas/details_miniview.html
<div class="container">
  
  <div class="row row-offcanvas row-offcanvas-right">
    
    <div class=" col-sm-9">
      <p class="pull-right visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
      </p>
      
        <h1>{{ idea.idea_title }}</h1>
      
      <div class="row">
        <ul>
          <li>{{ idea.idea_text }}</li>
        </ul>
        <p><a class="btn btn-default" href="{% url 'ideas:edit' idea.id %}" role="button">Edit details »</a></p>
      </div><!--/row-->
      
    </div><!--/.col-xs-12.col-sm-9-->
    
  </div><!--/row-->
  
</div><!--/.container-->

ideas/templates/ideas/edit.html
{% extends "common/base.html" %}


{% block container %}
    <div class="container">
 
      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>{{ idea.idea_title }}</h1>
            {{ form.non_field_errors }}
            <form action="" method="post">
              {% csrf_token %}
              <div class="input-group" id="{{ form.idea_title.id_for_label }}">
                <span class="input-group-addon" id="basic-addon1">Title</span>
                {{ form.idea_title }}
              </div>
              <div class="input-group" id="{{ form.idea_text.id_for_label }}">
                <span class="input-group-addon" id="basic-addon1">Description</span>
                {{ form.content }}
              </div>
              <div class="input-group" id="{{ form.idea_repo.id_for_label }}">
                <span class="input-group-addon" id="basic-addon1">Repo</span>
                {{ form.idea_repo }}
              </div>
              <div class="input-group" id="{{ form.idea_owner.id_for_label }}">
                <span class="input-group-addon" id="basic-addon1">Owner</span>
                {{ form.idea_owner }}
              </div>
              <div class="input-group" id="{{ form.idea_status.id_for_label }}">
                <span class="input-group-addon" id="basic-addon1">Status</span>
                {{ form.idea_status }}
              </div>
              <div class="input-group" id="{{ form.group.category_text.id_for_label }}">
                <span class="input-group-addon" id="basic-addon1">Group</span>
                {{ form.group }} <div> <a href={% url 'ideas:addgroup' %}>new group</a> </div>
              </div>
              </br>
              <button type="submit" class="btn btn-primary" name="save">Save</button>
            </form>
            <form action="" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary" name="delete">Delete</button>
            </form>
            
            <!--p>Ideas and dreams. Comes out to you from nowhere. And sometimes they flow away with
            the same way. Keep your ideas save fly with them and find collaborators.</p-->
          </div>
        </div><!--/.col-xs-12.col-sm-9-->
      </div><!--/row-->
      <hr>
    </div><!--/.container-->
{% endblock %}

ideas/templates/ideas/idea_list.html
{% extends "common/base.html" %}


{% block container %}
    <div class="container">
 
      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Groups</h1>
            
            <!--p>Ideas and dreams. Comes out to you from nowhere. And sometimes they flow away with
            the same way. Keep your ideas save fly with them and find collaborators.</p-->
          </div>
          <div class="row">
            {% if group_list %}
            <table class="table table-striped">
            {% for grp in group_list %}
            <div class="col-xs-6 col-lg-4">
              <a href="">{{ grp.idea_title }}</a>
        
                      
            </div><!--/.col-xs-6.col-lg-4-->
            </table>
            {% endfor %}
            {% else %}
            <p>No polls are available.</p>
            {% endif %}

     <!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Idea Description</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

          </div><!--/row-->
          
        </div><!--/.col-xs-12.col-sm-9-->

        {% block sidebar %}
        {% include "common/sidebar.html" %}{% endblock %}
      </div><!--/row-->
      <hr>
      
    </div><!--/.container-->
{% endblock %}

ideas/templates/ideas/idea_update_form.html
{% extends "common/base.html" %}


{% block container %}
    <div class="container">
 
      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>{{ idea.idea_title }}</h1>
            {{ form.non_field_errors }}
            <form action="" method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary" name="save">Save</button>
            </form>
            <form action="" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary" name="delete">Delete</button>
            </form>
            
            <!--p>Ideas and dreams. Comes out to you from nowhere. And sometimes they flow away with
            the same way. Keep your ideas save fly with them and find collaborators.</p-->
          </div>
        </div><!--/.col-xs-12.col-sm-9-->
      </div><!--/row-->
      <hr>
    </div><!--/.container-->
{% endblock %}

ideas/templates/ideas/index.html
{% extends "common/base.html" %}
{% block container %}
    <div class="container">
      <div class="row row-offcanvas row-offcanvas-right">

        <!-- put a col in the left to list the project as buttons -->
        {% block sidebar %}
        {% include "common/sidebar.html" %}

        {% endblock %}

        <div class="col-12 col-sm-8">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron-fluid">
            <h3>Beautiful Ideas</h3>
            {{ form.non_field_errors }}
            <form action="" method="post">
              {% csrf_token %}
              <div class="input-group" id="{{ form.title.id_for_label }}">
                <span class="input-group-addon" id="basic-addon1">Title      </span>
                {{ form.idea_title }}
              </div>
              <div class="input-group" id="{{ form.title.id_for_label }}">
                <span class="input-group-addon" id="basic-addon1">Description</span>
                {{ form.idea_text }}
              </div>
              <div class="input-group" id="{{ form.title.id_for_label }}">
                <span class="input-group-addon" id="basic-addon1">Group       </span>
                {{ form.group }}
              </div>
              <div class="input-group" id="{{ form.title.id_for_label }}">
                <span class="input-group-addon" id="basic-addon1">Repo        </span>
                {{ form.idea_repo }}
              </div>
              </br>
              <button type="submit" class="btn btn-primary">Save</button>
            </form>
            <!--p>Ideas and dreams. Comes out to you from nowhere. And sometimes they flow away with
            the same way. Keep your ideas save fly with them and find collaborators.</p-->
          </div>


          {% if latest_ideas_list %}

          {% for idea in latest_ideas_list %}
          <div class="row">
            <div class="col">
              <div class="card text-center">
                <div class="card-header">
                  <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                      <a class="nav-link active" href="{% url 'ideas:detail' idea.id %}">Description</a>
                    </li>
                    {% if idea.idea_repo %}
                      <li class="nav-item">
                      <a class="nav-link" href="{{ idea.idea_repo }}">Link</a>
                    {% else %}
                      <li class="nav-item disabled">
                      <a class="nav-disabled" href="{{ idea.idea_repo }}">Link</a>
                    {% endif %}
                    </li>
                    <li class="nav-item">
                      <a class="nav-link disabled" href="{% url 'ideas:groupview' idea.group.category_text %}" tabindex="-1" aria-disabled="true">{{ idea.group }}</a>
                    </li>
                  </ul>
                </div>
                <div class="card-body">
                  <h5 class="card-title">{{ idea.idea_title }}</h5>
                  <p class="card-text">{{ idea.idea_text }}</p>
                  <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
              </div>

            </div><!--/.col-xs-6.col-lg-4-->
          </div>
          {% endfor %}
          {% else %}
          <p>No polls are available.</p>
          {% endif %}

     <!-- Modal -->
          <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Idea Description</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  ...
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

        </div><!--/row-->

      </div><!--/.col-xs-12.col-sm-9-->

      </div><!--/row-->
    <hr>

</div><!--/.container-->
{% endblock %}

ideas/templates/ideas/login.html
{% extends "common/base.html" %}


{% block container %}
<div class="container">
  
  <div class="row row-offcanvas row-offcanvas-right">
    
    <div class="col-xs-12 col-sm-9">
      <p class="pull-right visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
      </p>
      <div class="jumbotron">
        <h1>Login</h1>
      </div>
      <div class="row">
        <p>test</p>
      </div><!--/row-->
      
    </div><!--/.col-xs-12.col-sm-9-->
  </div><!--/row-->
  <hr>
  
</div><!--/.container-->
{% endblock %}

ideas/templates/ideas/search_results.html
{% extends "common/base.html" %}


{% block container %}
<div class="container">
  
  <div class="row row-offcanvas row-offcanvas-right">
    
    <div class="col-xs-12 col-sm-9">
      <p class="pull-right visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
      </p>
      <div class="jumbotron">
        <h1>Results</h1>
      </div>
      <div class="row">
        {% if results_list %}
            <table class="table table-striped">
            {% for item in results_list %}
            
            <ul class="list-group">
              <div class="col-md-4 col-lg-8">
                
              <li class="list-group-item">
                <a href="">{{ item.idea_title }}</a>
                 <div class="col-md-4"> {{item.idea_text}} </div>
              </li>
              </div><!--/.col-xs-6.col-lg-4-->
              </ul>
            
            </table>
            {% endfor %}
            {% else %}
            <p>No results. Search unambiquis</p>
            {% endif %}
         </div><!--/row-->
      
    </div><!--/.col-xs-12.col-sm-9-->
    
    {% block sidebar %}
    {% include "common/sidebar.html" %}{% endblock %}
  </div><!--/row-->
  <hr>
  
</div><!--/.container-->
{% endblock %}