api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'ideas', views.IdeaViewSet)

app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

cloudsaver/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from ideas import views
from django.contrib.auth.models import User
from rest_framework import serializers, viewsets, routers

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('ideas/', include('ideas.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    #path('logout/', views.logout, name='logout'),
    path('', include('social_django.urls', namespace='social')),
    #path('tinymce/', include('tinymce.urls')),
    path('api', include('api.urls'), name='api'),
]

ideas/urls.py
from django.urls import path, include, re_path
from django.urls import reverse
from . import views
from .models import Idea
from rest_framework import routers


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'api', views.IdeaViewSet)

app_name = 'ideas'

urlpatterns = [
    #path('api', include(router.urls)),
    #path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('details/<int:pk>/', views.DetailMiniView.as_view(), name='detailmini'),
    path('<int:pk>/edit/', views.EditView.as_view(), name='edit'),
    # path('<int:id>/proposal/', include('tinymce.urls'), name='editor'),
    path('tinymce/', include('tinymce.urls')),
    path('add/', views.addView, name='add'),
    path('addgroup', views.AddGroup.as_view(success_url='/ideas/'),
         name='addgroup'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('results/', views.SearchResultsView.as_view(), name='search_results'),
    path('<str:slug>/', views.GroupView.as_view(), name='groupview'),
    
    path('contact', views.ContactView.as_view(), name='contact'),
    path('', include('social_django.urls', namespace='social')),
    
]

SOCIAL_AUTH_URL_NAMESPACE = 'social'

ideas/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
import datetime

# Create your models here.

class Ideas_Group(models.Model):
    category_text = models.CharField(max_length=30, unique=True)
    # votes = models.IntegerField(default=0)

    def __str__(self):
        return self.category_text

class Idea(models.Model):
    idea_title = models.CharField(max_length=30)
    idea_text = models.CharField(max_length=200)
    idea_repo = models.URLField(max_length=80, blank=True, null=True)
    idea_owner = models.CharField(max_length=30, blank=True, null=True)
    idea_status = models.CharField(max_length=30, blank=True, null=True)
    content = HTMLField('content')
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    group = models.ForeignKey(Ideas_Group, on_delete=models.CASCADE)
    
    def __str__(self):
        return "%s by %s => %s" % (self.idea_title, self.idea_owner, self.idea_text)

    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)
    

ideas/forms.py
from django import forms
from ideas.models import Idea, Ideas_Group
from django.forms.models import inlineformset_factory

class IdeasForm(forms.ModelForm):
    idea_title = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':"do you have a name for your idea",
        'aria-describedby':"basic-addon1",}))

    idea_text = forms.CharField(widget=forms.Textarea(attrs={
                                    'class':'form-control',
                                    'placeholder':"what s the idea man",
                                    'aria-describedby':"basic-addon1",
                                    'rows':"2"}),
                                max_length=200,)

    group = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':"Category",
        'aria-describedby':"basic-addon1",}))

    idea_repo = forms.URLField(widget=forms.URLInput(attrs={
        'class':'form-control',
        'placeholder':"repo",
        'aria-describedby':"basic-addon1",}),
                               required=False)

    class Meta:
        model = Idea
        fields = ('idea_title',
                  'idea_text',
                  'group',
                  'idea_repo',)

    def clean(self):
        group, created = Ideas_Group.objects.get_or_create(
                    category_text=self.cleaned_data.get('group'))
        self.cleaned_data['group'] = group
        return super(IdeasForm, self).clean()

    def save(self, commit=True):
        group, created = Ideas_Group.objects.get_or_create(
                    category_text=self.cleaned_data.get('group'))
        print(11111)
        self.cleaned_data['group'] = group
        #self.group = group_new.id
        print(222222)
        return super(IdeasForm, self).save(commit)

class EditIdeasForm(forms.ModelForm):
    idea_title = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':"do you have a name for your idea",
        'aria-describedby':"basic-addon1",}))

    idea_text = forms.CharField(widget=forms.Textarea(attrs={
                                    'class':'form-control',
                                    'placeholder':"what s the idea man",
                                    'aria-describedby':"basic-addon1",
                                    'rows':"10" }),
                                max_length=200,)

    idea_repo = forms.URLField(widget=forms.URLInput(attrs={
        'class':'form-control',
        'placeholder':"repo",
        'aria-describedby':"basic-addon1",}),
                               required=False)

    #idea_repo.widget.attrs.update(
    class Meta:
        model = Idea
        fields = ('idea_title',
                  'idea_text',
                  'idea_repo',
                  'idea_owner',
                  'idea_status',
                  'group')


    #def save(self, commit=True):


     #   if commit:

class AddGroupForm(forms.ModelForm):
    category_text = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':"New Group",
        'aria-describedby':"basic-addon1",}))

    class Meta:
        model = Ideas_Group
        fields = ('category_text',)

ideas/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from rest_framework import viewsets
from rest_framework.views import APIView
from .serializers import IdeaSerializer
from django.urls import reverse
from django.utils import timezone
import datetime

from .models import Idea, Ideas_Group
from .forms import IdeasForm, EditIdeasForm, AddGroupForm

class IdeaViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows ideas to be viewed or edited.
    """
    queryset = Idea.objects.all().order_by('-pub_date')
    serializer_class = IdeaSerializer

class IdeaApiView(APIView):

    def get(self, request, pk=None):
        res = get_object_or_404(Idea, pk=pk)
        
        return Response ({"msg": res, status:status.HTTP_200_OK})
 
# Create your views here.
class IndexView(generic.ListView):
    # model = Idea
    template_name = 'ideas/index.html'
    context_object_name = 'latest_ideas_list, ideas_list'
    
    #latest_ideas_list = Idea.objects.order_by('-pub_date')
    #paginator = Paginator(latest_ideas_list, 10)
    #latest_ideas_pages = paginator.page(1)
    def get(self, request):
        
        form = IdeasForm()
        latest_ideas_list = Idea.objects.order_by('-pub_date')
        paginator = Paginator(latest_ideas_list, 10)
        latest_ideas_pages = paginator.page(1)
        # ideas_list = Idea.objects.order_by('-pub_date')
        context = {
            'latest_ideas_list': latest_ideas_list[:6],
            'ideas_list': latest_ideas_pages,
            'form': form
        }
        return render(request,
                      self.template_name,
                      context)
    
    def post(self, request):
        if request.method == 'POST':
            # create a form instance and populate it with data from the request:
            print(request.POST)
            form = IdeasForm(request.POST)
            print(form.is_valid())    
            # check whether it's valid:
            if form.is_valid():
                ideapost = form.save(commit=False)
                #ideapost.pub_date=timezone.now()
                print(form.cleaned_data['group'])
                ideapost.save()

        latest_ideas_list = Idea.objects.order_by('-pub_date')[:6]
        paginator = Paginator(latest_ideas_list, 10)
        latest_ideas_pages = paginator.page(1)
        context = {
            'latest_ideas_list': latest_ideas_list,
            'ideas_list': latest_ideas_pages,
            'form': IdeasForm(),
        }
        return render(request,
                      self.template_name,
                      context)
            # if a GET (or any other method) we'll create a blank form
        #else:
        #   form = IdeasForm() 

        
class DetailView(generic.DetailView):
    model = Idea
    template_name = 'ideas/details.html'

    
class DetailMiniView(generic.DetailView):
    model = Idea
    template_name = 'ideas/details_miniview.html'

    
class EditView(generic.UpdateView):
    model=Idea
    template_name = 'ideas/idea_update_form.html'
    form_class = EditIdeasForm
    template_name_suffix = '_update_form'
    #redirect_url="ideas/details.html"
    def get_success_url(self):
        return reverse('ideas:index')

# def deleteView(request, id):
#     idea = Idea.objects.get(pk=id)
#     template_name = 'ideas/index.html'
#     idea.delete()
#     render(request, template_name)

# TODO: delete idea from the update view
class DeleteIdea(generic.DeleteView):
    model=Idea
    template_name = 'ideas/idea_update_form.html'
    template_name_suffix = '_update_form'
    #success_url='/'
    def get_success_url(self):
        return reverse('ideas:index')
    
def addView(request):
    #model = Idea
    template_name = 'ideas/add.html'
    return HttpResponse("Hey your ideas are awesome.")


class GroupView(generic.ListView):
    model = Idea
    template_name = 'ideas_group_list.html'
    paginate_by = 10
    
    context_object_name = 'group_list'
    
    def get_queryset(self):
      category_slug = get_object_or_404(Ideas_Group,
                                        category_text=self.kwargs['slug'])
      return Idea.objects.filter(group=category_slug)    
    
    
class AddGroup(generic.CreateView):
    model = Ideas_Group
    form = AddGroupForm()
    fields = ['category_text']

    
class AboutView(generic.TemplateView):
    template_name = 'ideas/about.html'

    
class ContactView(generic.TemplateView):
    template_name = 'ideas/contact.html'

    
class LoginView(generic.TemplateView):
    template_name = 'ideas/login.html'

    
def login(request):
    return render(request, 'login.html')


def logout(request):
    logout(request)
    return render(request, 'logout.html')


class SearchResultsView(generic.ListView):
    model = Idea
    template_name = 'ideas/search_results.html'
    context_object_name = 'results_list'

    def get_queryset(self):
        query = self.request.GET.get('q')
        results_list = Idea.objects.filter(Q(idea_title__icontains=query) |
                                   Q(idea_text__icontains=query))
        return results_list

ideas/templates/common/base.html
{% load static %}

<html lang="en">

{% block header %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Ideas</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'ideas/bootstrap.min.css' %}" />

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link rel="stylesheet" type="text/css" href="{% static 'ideas/ie10-viewport-bug-workaround.css' %}" />

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'ideas/offcanvas.css' %}" />

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!--script src="../../assets/js/ie-emulation-modes-warning.js"></script-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
     </head>
{% endblock %}

  <body>

{% block nav %}
<nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'ideas:index' %}">Ideas</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'ideas:index' %}">Home</a></li>
            <li><a href="{% url 'ideas:about' %}">About</a></li>
            <li><a href="{% url 'ideas:contact' %}">Contact</a></li>
          </ul>
          <form class="navbar-form navbar-left" action='{% url 'ideas:search_results' %}' method="get">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search" name="q">
            </div>
          </form>
          
          {% if not user.is_authenticated %}
          <p class="navbar-text navbar-right"> <a href="{% url 'social:begin' 'github' %}" class="navbar-link">Sign In</a></p>
          {% else %}
          <p class="navbar-text navbar-right"> <a href="{% url 'logout' %}" class="navbar-link">{{user.username}} Logout</a></p>
          {% endif %}
          <!--p class="text-right0"><a href="{% url 'ideas:contact' %}">login</a></span-->
        </div><!-- /.nav-collapse -->
        
      </div><!-- /.container -->
   
    </nav><!-- /.navbar -->

{% endblock %}
{% block container %}
{% include "common/sidebar.html" %}
{% endblock %}
{% block footer %}{% include "common/footer.html" %}{% endblock %}
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'idead/js/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'ideas/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'ideas/js/ie10-viewport-bug-workaround.js' %}"></script>
    <script src="{% static 'ideas/js/offcanvas.js' %} "></script>
    <!--Tinymce Text-Editor (Must be in Head Tag) -->
  <script src="{% static 'tinymce/tinymce.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'ideas/js/custom_tinymce.js' %}" ></script>
 
<script>
   $('#exampleModalCenter').on('show.bs.modal', function (event) {     
       var button = $(event.relatedTarget) // Button that triggered the modal
       var dlink = button.attr('href') // Extract info from data-* attributes
       $(this).find('.modal-body').load(dlink)
})
</script>
</body></html>

ideas/templates/common/footer.html
{% block footer %}
<footer>
  <p>© 2018, iob</p>
</footer>
{% endblock %}

ideas/templates/common/sidebar.html
{% block sidebar %}
<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
  <div class="list-group">
    {% if ideas_list %}

      {% for idea in ideas_list %}
        <a href="{% url 'ideas:detail' idea.id %}" class="list-group-item active">{{ idea.idea_title }} since {{ idea.pub_date }}</a>
      {% endfor %}
    {% endif %}
  </div>
  {% if ideas_list.has_other_pages %}
    <ul class="pagination">
      {% if ideas_list.has_previous %}
        <li><a href="?page={{ ideas_list.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in ideas_list.paginator.page_range %}
        {% if ideas_list.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if ideas_list.has_next %}
        <li><a href="?page={{ ideas_list.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}

  <!--Div Class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" -->
            </div
              </div><!--/.sidebar-offcanvas-->

{% endblock %}